zenoss/txwinrm

- txwinrm/util.py
We also need to reestablish the kerberos connection to make sure we are using the correct cipher.  This may be the cause of the bad request errors shwab is seeing.
> Fixes ZEN-15755

- txwinrm/util.py
> Work on ZEN-15915

- txwinrm/util.py
do manual cleanup in case destructor not called
> Fixes ZEN-16261

- txwinrm/util.py
> Fixes ZEN-16790

- txwinrm/util.py
By calling the step function we can easily get the krb_error.  This should really only happen on authentication.  We can revisit if we find other kerberos errors are returned differently in the future.  Also reworked the error messages so they match/make more sense.
> Fixes ZEN-14156

- txwinrm/util.py
When used on EL5, send/receive using unencrypted traffic.  To do this we will not set the confidentiality flag on the kerberos context.  'authGSSClientWrapIov' is only found on systems with kerberos v. 10 and up.  Also we need to be sure to set the header to use standard content as opposed to encrypted content.
> Fix for ZEN-16546

- txwinrm/shell.py
need to add timeout to all commands being sent
> Fixes ZEN-19214

- txwinrm/krb5.py
- txwinrm/util.py
Need a way to add a trusted realm into the krb5.conf file without hand-editing and setting immutable.
Also, did a little cleanup/pep8 updates
> Part I of fix for https://jira.zenoss.com/browse/ZEN-20543

- txwinrm/krb5.py
- txwinrm/util.py
This will show any kinit errors that occur.  especially useful for 'clock skew' errors
> Error reporting improvement

- txwinrm/util.py
Fixes ZEN-23238
We can pass over this error.  simply means that 2 or more kinits
are attempting to authenticate at the same time.
> Internal credential cache error ok

- txwinrm/SessionManager.py
- txwinrm/WinRMClient.py
some pep8 and other minor updates
> minor updates

- txwinrm/WinRMClient.py
> use lazy import for kerberos

- txwinrm/WinRMClient.py
Fixes ZPS-624
Need to take advantage of using the deferred semaphores when
sending wql requests so they go one at a time.  Windows only allows
one winrm request at a time.
> Use do_collect to enumerate for semaphores

- txwinrm/WinRMClient.py
> Remove invalid parameter, duplicate import

- txwinrm/WinRMClient.py
Fixes ZPS-741
* Call close_connection after 30 seconds to give more time for
other plugins to use the same connection.
* Windows/networks can close the connection on their end after a
timeout period, so we can't leave a connection open indefinitely.
> Close connections after 30 seconds, not immediately

- txwinrm/krb5.py
Fixes ZPS-583
* Allow for more than one kdc to be defined
* The first kdc added will be the admin_server
* If the krb5.conf is changed, this will allow for admin_server to
stay the same
* minor PEP8 stuff
> Allow for multiple kdcs to be used

- txwinrm/krb5.py
Fixes ZPS-583
* This will make it easier to supply more than one kdc
> Allow for comma separated list of kdcs

- txwinrm/shell.py
Fixes ZPS-874
* Remove the BOM from output.  Someone set us up the BOM
> Remove the BOM

- txwinrm/krb5.py
> strip off whitespace

- txwinrm/krb5.py
> Make sure profile message is in error.

- txwinrm/WinRMClient.py
Fixes ZPS-877
When sending a request, be sure that the session has actually started.
Seeing the decrypt integrity check also, but was happening around
'NoneType' has no attribute 'send_request' errors.
> Make sure session is open before sending requests

- txwinrm/WinRMClient.py
Fixes ZPS-877
* Seeing decrypt integrity issues and message stream modified errors.
> Change close connection timeout to 30s

- txwinrm/WinRMClient.py
- txwinrm/util.py
> Handle Exception and issue error message

- txwinrm/util.py
> fix attribute error

- txwinrm/krb5.py
Fixes ZPS-2109
Fixes NoneType is not iterable error
> Check for TypeError when looking for string in None

- txwinrm/shell.py
> Fix traceback in log

- README.rst
- txwinrm/winrs.py
This will make it quicker and easier to execute a powershell script
against a windows device.  Updated docs for usage and examples.
> Add powershell as a winrs mode

- txwinrm/WinRMClient.py
- txwinrm/enumerate.py
- txwinrm/shell.py
- txwinrm/util.py
- txwinrm/winrm.py
Fixes ZPS-2829
update logging messages to show host name or ip
Also updated the winrm command to allow for multiple wql filters and to query namespaces other than root
> add logging, fix for task locking up

- txwinrm/twisted_utils.py
Fixes ZPS-2940
Remove print statement.  used for debugging
> remove print statement

- txwinrm/WinRMClient.py
- txwinrm/shell.py
- txwinrm/util.py
Fixes ZPS-2176, ZPS-2480
conn_info was still being referenced.  we'll make a deep copy instead so that memory use doesn't grow because of it
cpu usage is most likely tied to this memory usage
> Fix memory leak

- txwinrm/WinRMClient.py
- txwinrm/util.py
Fixes ZPS-2176
No need to keep making copies of conn_info.  this will create one when needed then update it with new values
> no need to make copies of ConnectionInfo

- txwinrm/WinRMClient.py
- txwinrm/util.py
Fixes ZPS-3216
If we start initiating a connection and the ticket expires before we finish the connection in gss_client.get_username, we should just start over with a new ticket.  the perils of continuous data collection continue.
> handle ticket expiration timing

- txwinrm/WinRMClient.py
- txwinrm/util.py
fixes ZPS-5471
make error messages make more sense and give better troubleshooting info to the exceptions.  some pep8 stuff.  also removed superfluous code from WinRMClient which was duplicating _authenticate_with_kerberos error handling
> update error messages

- txwinrm/WinRMClient.py
fixes ZPS-5087
we need to check for an established connection before attempting to check the current kerberos ticket lifetime.  will cause an exception and no other client will be able to use the session.  if we do a reset of the connection, we need to initiate a new one
> wait for established connection before checking krb tkt lifetime

- txwinrm/WinRMClient.py
fixes ZPS-5568, ZPS-4940
also, run_command was trying to raise a non-Exception based error.  also, get the correct error response message in handler
> be sure not to kill off session's agent

- txwinrm/WinRMClient.py
> be sure exceptions get raised on request error

- txwinrm/WinRMClient.py
fixes ZPS-5568, ZPS-5323
also make sure we're raising Exception based exceptions.
> make sure we have context for checking ticket lifetime

- txwinrm/WinRMClient.py
Fixes ZPS-4940
also, these changes will allow us to run a command that lasts longer than 60s if it has continual output
> raise exceptions so we don't get caught raising None

- txwinrm/WinRMClient.py
> fix number of args sent to function

- txwinrm/WinRMClient.py
fixes ZPS-5767
we should retry the "Unexpected Response" request.  if we get it again, then we'll remove the encrypted payload, which is actually just the request that we sent.
> fix for "Unexpected Response" errors

- txwinrm/util.py
Fixes ZPS-5770
if windows server does not return the WWW-Authenticate header in the response, we should handle this.  this is some sort of error with windows responses, maybe due to out of date Windows Management Framework.  there are many bugs in the old WMF, and this could be one of them.
> account for possible missing authentication header from windows

- txwinrm/WinRMClient.py
- txwinrm/collect.py
fixes ZPS-5797
wait another second to let the krb ticket fully expire, then continue.  also check the lifetime on our active connection so we can reset it if needed.  update test collect module for testing expiring tickets
> fully allow tickets to expire

- txwinrm/WinRMClient.py
fixes ZPS-5918
network timeout errors in the log indicate we could be trying to reuse a bad connection.  we need to be sure we're saving off a new connection when it's created and destroy the bad connection.  RequestErors are ok to keep the same connection as they should still be valid.  removed unused imports
> be sure to save new connection when retrying request

- txwinrm/WinRMClient.py
fixes ZPS-5819
the timeout error could just be that the connection went bad.  let's try one more time
> retry with new connection on TimeoutError

- txwinrm/util.py
> Fix blocking code for kerberos
