txwinrm/request/create.xml

User reported a fix for performance counter localization on the wiki page.  Changing WINRS_PROFILE to false, installing english language, and setting the monitor user to use english as a language fixed his problem.  We will test out using the profile.  Not sure why it was taken out in the first place so we'll need to let QA run some tests.

Possible fix for ZEN-9497

---

README.rst

The syntax to be used on windows is wrapping the configurations in '', otherwise there is an error stating:
Error: Invalid use of command line. Type "winrm -?" for help.

Update winrm windows syntax

---

txwinrm/shell.py
txwinrm/util.py

We should close connections out as soon as we encounter a timeouterror.  this will allow us to reestablish a connection more quickly.

Fixes ZEN-22558

---

txwinrm/util.py

Fixes ZEN-22767
should be `_pool` instead of `pool`

Fix typo for closeCachedConnections call

---

txwinrm/enumerate.py

Fixes ZEN-22558
ResponseFailed/RequestErrors are ok to receive, no need to close
connections.  Doing this caused a hiccup in the last exception
caught to show an ImportError for pysamba.twisted.reactor.

don't close connection for these errors

---

txwinrm/app.py
txwinrm/util.py

Fixes ZEN-22880
This change negates the need for DNS lookup in twisted when sending
a request to a Windows server.  It should both speed up requests
and allow for devices with no name resolution to be contacted.
Also added the --ipaddress,-s switch to winrm/winrs to enter
the ip address of the device.

Send request to ip address instead of fqdn

---

txwinrm/krb5.py

Fixes ZEN-23183
When password expires, we need to send this information back.
kinit errors are raised as exceptions.

Check for expired password in kinit

---

txwinrm/SessionManager.py
txwinrm/WinRMClient.py
txwinrm/app.py
txwinrm/shell.py
txwinrm/util.py
txwinrm/winrm.py
txwinrm/winrs.py

Fixes ZEN-24477
This adds SessionManager to manage single connections to a device to
cut down on DNS lookups for kerberos.  it will also allow for using a
single connection to run enumerations and single commands.  Because of
Windows limitations, conversations must be completed before a new
operation can start.  So all single commands and enumerations will
have to run sequentially.  Long running commands will need their own
connection.  Changed cli app to use the new clients.
Also, added support for using the WSMAN service principal name

Add classes to support sending commands through single connection

---

txwinrm/WinRMClient.py

Fixes ZEN-26033
kerberos.so could either not be installed yet or could have been
removed during uninstall.

kerberos may not exist during install/removal

---

txwinrm/WinRMClient.py
txwinrm/associate.py

Fixes ZPS-479
First part of update for Windows Hard Disk component.  We'll need
to use the 'associators of' query to map hard disks and file systems.
This will also be useful for other plugins, interfaces and iis.
Allow for nested association calls, update test script

Add AssociatorClient for 'Associators of' WQL query

---

txwinrm/WinRMClient.py
txwinrm/enumerate.py
txwinrm/request/command.xml
txwinrm/request/create.xml
txwinrm/request/delete.xml
txwinrm/request/enumerate.xml
txwinrm/request/event_pull.xml
txwinrm/request/pull.xml
txwinrm/request/receive.xml
txwinrm/request/send.xml
txwinrm/request/signal.xml
txwinrm/request/subscribe.xml
txwinrm/request/unsubscribe.xml
txwinrm/util.py

Fixes ZPS-82
* User can supply envelope size if set to larger in Windows
* Catch exception when parsing xml

Allow for user to specify envelope size in requests

---

txwinrm/WinRMClient.py
txwinrm/request/command.xml
txwinrm/request/create.xml
txwinrm/request/delete.xml
txwinrm/request/event_pull.xml
txwinrm/request/receive.xml
txwinrm/request/send.xml
txwinrm/request/signal.xml
txwinrm/request/subscribe.xml
txwinrm/request/unsubscribe.xml
txwinrm/shell.py
txwinrm/util.py

Fixes ZPS-554
* Allow user supplied code page, default to 65001
* Allow user supplied locale, default to en-US
* Allow user supplied encoding, default to utf-8
* Added function to build powershell command line.  shlex splits
the script itself into separate arguments when it should be just
one.  SingleCommandClient and LongCommandClient will accept the
powershell command line with options along with the script in a
separate parameter, ps_script

Add support for winrm localization

---

txwinrm/WinRMClient.py

Fixes ZPS-741
* Found after testing that 60 seconds was a better delay to use.
* Made the long running command key more unique by including the
powershell script as part of it. Ran into issues without it

Increase delayed close_connection to 60s

---

txwinrm/krb5.py
txwinrm/test/test_connection_info.py
txwinrm/util.py

Fixes ZPS-617
* Allow user to specify krb5.conf includedir for special kerberos
considerations like disabling rdns
* This will let users make any necessary changes for their krb5.conf
* Make sure to take empty includedir into account

Add ability to specify extra include directory for kerberos

---

txwinrm/app.py
txwinrm/krb5.py

Fixes ZPS-617
* Run klist which loads the config file.  if there's an error,
then do not add the includedir

Add test for valid includedir

---

txwinrm/util.py

- Fixes ZPS-867
- Added generic exception handling to _parse_error_message to deal with
unexpected output

Fix traceback for unhandled parse error (ZPS-867)

---

txwinrm/WinRMClient.py

Since run_command currently suppresses exceptions, these do not get
picked up downstream and cannot be handled by PythonCollector onError
methods used by ShellDatasource, etc

SingleCommandClient should raise exceptions when run_command fails

---

txwinrm/WinRMClient.py

Fixes ZPS-913
if no results from seed_class we need to raise an exception as a KeyError is misleading

semaphore is not raising correct exception

---

txwinrm/app.py
txwinrm/krb5.py
txwinrm/util.py

Default is true, so no need to set it if not disabling rdns.
User could have optional config file which disables it, so do not
add conflicts.

Only set rdns option when specifically told to disable it

---

txwinrm/WinRMClient.py
txwinrm/shell.py
txwinrm/util.py

Fixes ZPS-1354
If we get a 500 error trying to stop the get-counter cmdlet, let's
try it twice more.  continue processing so that we can delete the
remote shell.
Also, if we get a ConnectError, this could be a network timeout that
occurs on a connection closed by other side, but not by us.  This way
we won't keep trying to send requests on a dead connection.

updated handling of 500 error. reset connection on network timeout

---

txwinrm/SessionManager.py
txwinrm/WinRMClient.py

Fixes ZPS-1584
Holding onto the SESSION_MANAGER and individual session inside a
client was causing a reference cycle during garbage collection.
Fixed so that we don't hold onto the actual references.

Fix reference cycle in session managment

---

txwinrm/WinRMClient.py
txwinrm/twisted_utils.py

Cases were found where operations running under the session's
DeferredSemaphore(1) would encounter network timeouts during their
connection. This would result in the semaphore being permanently
acquired, and prevent all further operations requiring the semaphore
from running until the process was restarted.
This change adds a mandatory timeout to all operations running under the
session's semaphore to prevent this to make sure that the semaphore
never gets into a permanently-acquired state.
Refs ZPS-1765.

Mandatory timeout for DeferredSemaphore(1)

---

txwinrm/WinRMClient.py
txwinrm/twisted_utils.py

DeferredSemaphore.run(fn, *args, **kwargs) has the method signature it
does because it defers the creation of the fn(*args, **kwargs) deferred
until the semaphore can be acquired. My change to wrap a timeout around
all functions run under the semaphore in e5ca422 broke this by causing
fn(*args, **kwargs) to be executed before the semaphore could be
acquired.
This change restores the execution of fn(*args, **kwargs) to after the
semaphore is acquired, and thus fixes the resulting 'kerberos'
referenced before assignment problems it caused in the Windows ZenPack.
Refs ZPS-1795.

Fix 'kerberos' referenced before assignment

---

txwinrm/request/enum_shells.xml
txwinrm/request/pull_shells.xml
txwinrm/shell.py
txwinrm/util.py

Fixes ZPS-1770
If server reboots or shell is deleted, we'll need to create a new one

	Test if current shell id is active for LongRunningCommand

---

txwinrm/SessionManager.py
txwinrm/WinRMClient.py
txwinrm/util.py

Fixes ZPS-1584
SessionManager was holding onto references to WinRMSessions. HTTPConnectionPools
were not being deleted either.  These changes seem to have curbed memory growth.

Fix memory leaks

---

txwinrm/SessionManager.py
txwinrm/WinRMClient.py
txwinrm/shell.py
txwinrm/util.py

keep sessions and agents around.  we'll only have to reallocate them later.  doesn't add any new burdens to zenpython
Fixes ZPS-1851, ZPS-1584

we should not delete pool.  allow twisted to take care of it

---

txwinrm/WinRMClient.py
txwinrm/shell.py

Since we can simultaneously create commands on a single shell, there is no need to keep creating new ones.  we will create one on initial startup, either through zenmodeler or zenpython, then keep using it.
Fixes ZPS-1354

Implement use of single shell on windows host

---

txwinrm/SessionManager.py
txwinrm/WinRMClient.py

keep agent.  just close cached connections and reconnect.  related
to previous fix in 1.2.24 which introduced keeping agents around.
Also, set twisted Factory.noisy to False just in case there are
twisted logs holding onto factory references, which causes memory leaks.

No need to reset agent in WinrmSession.

---

txwinrm/WinRMClient.py
txwinrm/shell.py
txwinrm/util.py

When the concurrent operations has been exceeded for winrm, we start
to see these errors.  This message will let users know how to fix it.
Increase the winrm config option and restart the winrm service or at
least restart the service.
also, removed extra call to get_active_shell() in long running command.
https://windowsserver.uservoice.com/forums/301869-powershell/suggestions/15669870-winrm-concurrent-operations-increase-to-eventual

Add resolution to error message for concurrent operations

---

txwinrm/WinRMClient.py
txwinrm/krb5.py
txwinrm/util.py

Fixes ZPS-2072
When yielding to the klist process in add_includedir, we could have
lost control of writing the krb5.conf file.  now we will just write
it out, then check for an error from kinit.  if there is one then
remove the includedir and try again

don't use klist to determine bad includedir

---

txwinrm/SessionManager.py
txwinrm/WinRMClient.py
txwinrm/request/pull_shells.xml
txwinrm/shell.py

This update will allow us to use a single shell per device.  On a service
startup, like zenpython, we'll probably end up with a few shells.  After
running for a while, all clients will start to use the longest running
shell owned by a specific user.  After a daemon restart, if the shell has
not timed out, we can reconnect to it and continue as if nothing happened.
On Session logout, remove the shell for the device ip.  On the next query,
retrieve the oldest running session.  This will be good for services like
zenmodeler that do not run very often.
This also takes into account older versions of windows zp or other zenpacks
that are not using this version of txwinrm.

Keep number of open shells as low as possible

---

txwinrm/SessionManager.py
txwinrm/WinRMClient.py
txwinrm/shell.py
txwinrm/util.py
txwinrm/winrs.py

Revert reusing a single shell for lifetime of collection
Fixes ZPS-2132
Long commands will create a shell, then delete it when done.
Revert single shell usage for single/long commands.  will revisit this at a later date.

Fix so that we will use a single shell for short commands

---

txwinrm/WinRMClient.py

Fixes ZPS-2738
kerberos is a global variable, not local.  also, import it directly
as it may not have been imported in util yet.

make kerberos global

---

README.rst
txwinrm/SessionManager.py
txwinrm/WinRMClient.py
txwinrm/app.py
txwinrm/twisted_utils.py
txwinrm/util.py

Fixes ZPS-2829
Added a connection timeout so that we can return quicker from a failed connection
This will allow for fewer tasks to be in a running state.  connections should only take a few seconds at most
Pool connections seem to keep growing in memory.  Destroy agent and connection pool when closing a connection
Also allow for starting an immediate close connection

Add connection timeout option, possible memory leak fix

---

txwinrm/SessionManager.py
txwinrm/WinRMClient.py
txwinrm/util.py

Fixes ZPS-2394, ZPS-2963
during modeling, we were obtaining spn tickets in parallel when trying to query wmi and powershell.  this is creating two tickets in the cache.  modeling was still working, but we really should only do this once.
the agent was not being reallocated for basic auth for a long running command so we need to make sure we get a new agent
also made it so that we consistently close a connection when attempting a retry or when we are finished with a connection
a better way to abort a close connection is to see if the deferred has been cancelled

updates for dealing with closing connections. also kerberos

---

txwinrm/SessionManager.py
txwinrm/WinRMClient.py

Fixes ZPS-3097
UnauthorizedError is a subclass of RequestError, so it was being caught by the first except.  let's just close up connections and raise the exception
Be sure we're connected and have an agent to send an enumerate request

Fix error handling from semaphore

---

txwinrm/WinRMClient.py

Fixes ZPS-2712
The headers were never updated with the new conn_info changes after a password change.  this will allow us to recreate the headers when correct settings are passed in

reset headers and url in reset_all

---

txwinrm/collect.py
txwinrm/util.py

Fixes ZPS-3097
Set self._url to None on a reset so that we can reset headers and get a new agent.
Also, we can make the WinrmCollectClient use EnumerateClient

Ensure we have an agent to send a request

---

txwinrm/util.py

Fixes ZPS-2963
since we were not adding authorization back into the header on the new connection we were failing over and over

authorization was not added back into the header

---

txwinrm/collect.py

Fixes ZPS-3144
HyperV Zenpack relies on create_winrm_client being imported into collect

Revert removal of importing create_winrm_client

---

txwinrm/shell.py

Fixes ZPS-3377
Be sure that command id is also none so that we don't try to receive anything from a non-existent shell.

reset command id along with shell id

---

txwinrm/test/usertest.ini
txwinrm/test/usertest.py
txwinrm/util.py
txwinrm/winrs.py

Fixes ZPS-3564
use a single semaphore so that we are using the correct credentials cache for a multi-user environment.  added functional test to assert actual user in gssclient context is the one requested.

ensure correct KRB5CCNAME is used when getting ticket

---

README.rst
txwinrm/WinRMClient.py
txwinrm/util.py
txwinrm/winrs.py

Fixes ZPS-5490
when handling a response, we were resetting the gssclient, or kerberos context, before we had a chance to decrypt the reponse message.  this decrypts the message first and will continue as it should.  also, no need to try and receive from a command that has already exited. updated the winrs command line utility also.

fix decrypt integrity check error

---

txwinrm/WinRMClient.py
txwinrm/test/usertest.ini
txwinrm/test/usertest.py
txwinrm/twisted_utils.py
txwinrm/util.py

Fixes ZPS-3564
the deferredSemaphore performing authGSSClientStep was executing too quickly and occasionally the wrong credential cache will be used. this will ensure that only one connection is created at a time and that the correct credentials will be used. also add in common check for ResponseNeverReceived so we don't error on cancels that we cause.

only init one connection at a time to allow multiple users

---

txwinrm/WinRMClient.py
txwinrm/util.py

fixes ZPS-5087
this can cause an error when connecting using a stale conn_info that does not have the connect_timeout attribute.  root cause for 'NoneType' has no attribute 'getConnection' seems to be an out of date kerberos.so module.

be sure conn_info has connect_timeout attribute

---

txwinrm/WinRMClient.py
txwinrm/collect.py

Fixes ZPS-5510
when we were retrying a request we were raising an error if it turned out to be ok. now we'll return the response data. other fixes around an expiring ticket and readability.  improved testing if session was connected.  created a test in collect.py to prove the expiration handling.  the test will defer until there's less than 60s left in the ticket lifetime, then allow the handler to wait for the ticket to expire and create a new connection

return an OK response, kerb context fixes

---

txwinrm/WinRMClient.py
txwinrm/collect.py

Fixes ZPS-5323, ZPS-5557
because _reset_all() was yielding to the close_cached_connection() deferred, another request was able to sneak through and initiate a new connection. after the connections were closed, the agent was destroyed, which caused an error when we try to use the agent. by resetting everything and firing a deferred to close the connection, we can continue normally with a new session. found during testing that gssclient could have been reset before trying to encrypt the body, so we'll make sure we have a valid connection.

reset session variables before creating new connection

---

txwinrm/WinRMClient.py

fixes ZPS-5588
returnValue caused the response to be None, hence the NoneType has no attribute errors.  also, update error message for the difference between kerberos and basic UnauthorizedErrors(401).

remove returnValue from non-deferred call

---

txwinrm/winrs.py

fixes ZPS-5700
winrs single was always emitting full results in dictionary form. recent changes printed stdout/stderr as lines.  customer was depending on previous style of output

revert change to winrs single output

---

txwinrm/WinRMClient.py

Fixes ZPS-5727
nothing was being yielded in WinRMSession._deferred_logout, so simply a returnValue was causing the traceback.  we'll now yield a success so that it is a generator again.
removed inlinecallbacks decorator

fix non-generator error with deferred logout

---

txwinrm/WinRMClient.py
txwinrm/app.py
txwinrm/util.py
txwinrm/winrs.py

fixes ZPS-3757, ZPS-5822, ZPS-5797
This update will no longer use Session Management. There were too many moving parts and points of failure.  We will tie the request and connection close together so that we are not destroying a connection while trying to create a one to use.  each instance of a client will maintain it's own connection to a windows device.  fixed the delay of an expiring kerberos ticket so that it actually "sleeps" while waiting for it to expire.  for each request, we will wait for the previous request to finish, then reuse the connection.  if there is no connection, we will create a new one.  also added "operation_timeout" to the command line so that we can test adjusting the operation timeout of winrm/winrs on the command line.  changed the connect timeout of the agent …

simplify winrm connections

---

README.rst
txwinrm/krb5.py
txwinrm/util.py

this will use the kerberos credential cache collections so that we do not need to specify a cache name and kerberos can easily switch between the different caches on it's own.

make use of credential cache collections

---

txwinrm/WinRMClient.py
txwinrm/collect.py
txwinrm/krb5.py
txwinrm/util.py

Fixes ZPS-5797
this will give the ability to automatically renew the kerberos user ticket so that we do not see an issue with attempting to use an expired context.  we will initiate a deferred that will fire 5 minutes (by default) before a ticket expires.  the first connection will add the one and only deferred per user and will call 'kinit -r user@DOMAIN'.  also found that using 'klist -l' may truncate the full user name.  we'll use 'klist -A' instead so that we can get the full user names for all caches.  added a simple test function in collect to make sure that user_in_klist is performing as expected.

add ability to auto renew kerberos tickets

---

README.rst
txwinrm/collect.py
txwinrm/krb5.py
txwinrm/test/usertest.py
txwinrm/util.py

credential cache collections only support one user per domain. insufficient for our needs so we need to use a semaphore to ensure we are using the correct cache name for a given user

revert using credential cache collection

---

txwinrm/util.py

fixes ZPS-5926
adding another condition for multiple clients trying to kinit at the same time. this will allow the first kinit to succeed, then simply get an spn to use

add another kinit exception to pass
